### ISSUE TITLE
Retry on 500 errors

### ISSUE THREAD

**Issue by stoewer** [stoewer/go-nakadi#15]
The http helper methods `httpGET`, `httpPUT`, `httpPOST`, and `httpDELETE` in [nakadi.go](https://github.com/stoewer/go-nakadi/blob/master/nakadi.go) will retry http requests when they fail to make the request (e.g. Nakadi is down).

Those methods should also retry when the request returns with 500 errors.

**Comment by snowyleopardz** [comment]
Lets begin

**Comment by MorrisLaw** [comment]
How do I assign myself this issue ?

**Comment by stoewer** [comment]
Just leave a comment that you would like to work on this issue

**Comment by MorrisLaw** [comment]
Ok , I'll be working on this issue.

**Comment by stoewer** [comment]
@MorrisLaw are you still working on this one? Otherwise I'd like to take this one over.

**Comment by MorrisLaw** [comment]
You can take it
