### ISSUE TITLE
Batch size is limited to 10.

### ISSUE THREAD

**Issue by pzaleski** [stoewer/go-nakadi#32]
Library is not providing option to configure [max_uncommitted_events](https://zalando.github.io/nakadi/manual.html#/subscriptions/subscription_id/events_get*max_uncommitted_events), so default nakadi value will be used - `10`.

When stream has 10 uncommitted events, it will pause. In practice that means setting `BatchLimit` to value higher that 10, won't be effective, since actual batch size is upper bounded by max_uncommitted_events.

go-nakadi should support setting max_uncommitted events for stream.

**Comment by krnkl** [comment]
Thats true, `max_uncommitted_events` should be configurable. I'll check you PR.
Thanks

**Comment by stoewer** [comment]
Resolved via #33
