### ISSUE TITLE
Replace 'unblock' channels in mocks with 'WaitUntil'

### ISSUE THREAD

**Issue by stoewer** [stoewer/go-nakadi#5]
Many mocks used for unit testing use a channel called `unblock` in order to delay method invocation:

```go
type someMock struct {
	mock.Mock
	unblock chan struct{}
}
```

This kind of constructs could be replaces with functionality provided by the used [mocking library](https://github.com/stretchr/testify), which has already a function called [WaitUntil](https://godoc.org/github.com/stretchr/testify/mock#Call.WaitUntil) that does the exact same thing.

Therefore all existing uses of `unblock` channels can be replaced with more idiomatic code.

**Comment by krnkl** [comment]
Will take this issue
