### ISSUE TITLE
Make retry for `CommitCursor` optional

### ISSUE THREAD

**Issue by stoewer** [stoewer/go-nakadi#6]
Retries with exponential back-off can be turned in all sub APIs of `go-nakadi`, the only exception is the method `CommitCursor` of the `StreamAPI` where retries are enabled all the time. In order to be more consistent with other sub APIs, retries should be also optional for  `CommitCursor`.

The option struct `StreamOptions` must have a field `CommitRetry` and retry should only be enabled of the field is set to `true`.

**Comment by MorrisLaw** [comment]
What would this involve, aside from adding `CommitRetry bool` to the StreamOptions struct ? How should I test the functionality in streams_test ? 

I'm new to golang, and want to take this opportunity to learn it, thank you ahead of time for you patience.

**Comment by stoewer** [comment]
> What would this involve, aside from adding CommitRetry bool to the StreamOptions struct ? How should I test the functionality in streams_test ?

Adding `CommitRetry` to the options is just the first step. The second is to actually prevent the retry, this can be achieved by initializing the `commitBackOff` with a `backoff.StopBackOff` instead of the currently used exponential back-off (unless of course `CommitRetry` is true).

> I'm new to golang, and want to take this opportunity to learn it, thank you ahead of time for you patience.

No worries, just give it a try and make a pull request. If you have any further questions just ask.

**Comment by MorrisLaw** [comment]
Thank you, I'll be working on this as well.
